<?php

namespace tests;


use PHPUnit\Framework\TestCase;

class BasicTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function test_things_can_be_bootstrapped()
    {

        $this->assertEquals(true, 1, "true is true");

    }

}
